# Generated by Django 5.1.6 on 2025-03-05 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free_trial', models.BooleanField(default=False)),
                ('free_trial_start_date', models.DateTimeField()),
                ('free_trial_billing_cycle', models.CharField(verbose_name=(('daily', 'DAILY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY')))),
                ('free_trial_end_date', models.DateTimeField()),
                ('billing_cycle', models.CharField(verbose_name=(('daily', 'DAILY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY')))),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(verbose_name=((('active',), 'ACTIVE'), (('to_expire',), 'TOEXPIRE'), (('expired',), 'EXPIRED')))),
                ('currency', models.CharField(verbose_name=(('naira', 'NAIRA'), ('dollars', 'DOLLARS'), ('pounds', 'POUNDS'), ('euros', 'EUROS')))),
                ('notification_period', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
