# Generated by Django 5.1.6 on 2025-03-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(verbose_name=(('daily', 'DAILY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(verbose_name=(('naira', 'NAIRA'), ('dollars', 'DOLLARS'), ('pounds', 'POUNDS'), ('euros', 'EUROS'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='free_trial_billing_cycle',
            field=models.CharField(verbose_name=(('daily', 'DAILY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(verbose_name=((('active',), 'ACTIVE'), (('to_expire',), 'TOEXPIRE'), (('expired',), 'EXPIRED'))),
        ),
    ]
