# Generated by Django 5.1.6 on 2025-03-08 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_domain'),
        ('subscription', '0002_alter_subscription_billing_cycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='service.service'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(verbose_name=(('daily', 'DAILY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(verbose_name=(('naira', 'NAIRA'), ('dollars', 'DOLLARS'), ('pounds', 'POUNDS'), ('euros', 'EUROS'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='free_trial_billing_cycle',
            field=models.CharField(verbose_name=(('daily', 'DAILY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(verbose_name=((('active',), 'ACTIVE'), (('to_expire',), 'TOEXPIRE'), (('expired',), 'EXPIRED'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
