# Generated by Django 5.1.6 on 2025-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_billing_cycle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='next_billing_date',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(verbose_name=(('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(verbose_name=(('naira', 'NAIRA'), ('dollars', 'DOLLARS'), ('pounds', 'POUNDS'), ('euros', 'EUROS'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='free_trial_billing_cycle',
            field=models.CharField(verbose_name=(('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(verbose_name=((('active',), 'ACTIVE'), (('to_expire',), 'TOEXPIRE'), (('expired',), 'EXPIRED'))),
        ),
    ]
