# Generated by Django 5.1.6 on 2025-03-08 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_rename_start_date_subscription_current_billing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(verbose_name=(('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(verbose_name=(('naira', 'NAIRA'), ('dollars', 'DOLLARS'), ('pounds', 'POUNDS'), ('euros', 'EUROS'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='free_trial_billing_cycle',
            field=models.CharField(verbose_name=(('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(verbose_name=((('active',), 'ACTIVE'), (('to_expire',), 'TOEXPIRE'), (('expired',), 'EXPIRED'))),
        ),
    ]
