# Generated by Django 5.1.6 on 2025-03-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_subscription_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(verbose_name=(('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(verbose_name=(('naira', 'NAIRA'), ('dollars', 'DOLLARS'), ('pounds', 'POUNDS'), ('euros', 'EUROS'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='free_trial_billing_cycle',
            field=models.CharField(null=True, verbose_name=(('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY'))),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(verbose_name=((('active',), 'ACTIVE'), (('to_expire',), 'TOEXPIRE'), (('expired',), 'EXPIRED'))),
        ),
    ]
