# Generated by Django 5.1.6 on 2025-03-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
