# Generated by Django 5.1.6 on 2025-03-03 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code_timeout',
            new_name='verification_code_expiresat',
        ),
    ]
