# Generated by Django 5.1.6 on 2025-03-03 19:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'null': 'Please provide a phone number', 'unique': 'A user with this phone number already exists'}, max_length=128, region=None, unique=True),
        ),
    ]
