# Generated by Django 5.1.6 on 2025-03-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code_expires_at',
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('register', 'REGISTER'), ('forgot_password', 'FORGOT_PASSWORD'), ('change_password', 'CHANGE_PASSWORD')], default='register', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
