# Generated by Django 5.1.6 on 2025-03-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='consumed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
