# Generated by Django 5.1.6 on 2025-03-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_code_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='type',
            new_name='verification_type',
        ),
    ]
